### ISSUE TITLE
Not search inheritance in folder with dot.

### ISSUE THREAD

**Issue by ghost** [adammockor/pug-inheritance#15]
Hi @adammockor!
Thank you for this project!

I have folder with a dot as its first character In my project.

Could you add option for a glob?
https://github.com/adammockor/pug-inheritance/blob/master/src/parser.js#L44
let files = glob.sync(`${this.directory}/**/*${this.extension}`, {dot:true});

**Comment by adammockor** [comment]
Will do.

**Comment by adammockor** [comment]
Updated in `3.0.0-beta.1`.
