### ISSUE TITLE
Not worked in global install

### ISSUE THREAD

**Issue by Hinaser** [adammockor/pug-inheritance#17]
Because it assumes that `package.json` always exist in working folder, there are good chances npm modules fails if it depends on `pug-inheritance` and there is no `package.json` in working folder, especially installed with global option.

Need a patch that `pug-inheritance` works whether `package.json` exists.

I think this shoud be treated as emergent because through `gulp-pug-inheritance`, there should be numbers of people affected by this issue.

**Comment by Hinaser** [comment]
I made a PR (#16).
Please review and merge it.

Best regards.

**Comment by adammockor** [comment]
Thank you.

Version was bumped to `3.0.0-beta.2`.
