### ISSUE TITLE
Switch to .pug

### ISSUE THREAD

**Issue by adammockor** [adammockor/pug-inheritance#9]
I already did in my company without issues, so I guess pug is stable enough?

**Comment by pure180** [comment]
I don't use Jade anymore, switched to Pug in all of my projects and I'm facing no issues as well. So guess we can give it a go?

**Comment by adammockor** [comment]
Ok, so I will look into it over the weekend

**Comment by pure180** [comment]
I can do it too? But you have to merge and publish it then?

**Comment by adammockor** [comment]
Of course if you have time. 👍
